load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "unrelated_paralel_machine_generator",
    srcs = ["unrelated_paralel_machine_generator.py"],
    deps = [
        "//config:config_handler",
        "//third_party:numpy",
        "//third_party:pandas",
    ],
)
