load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "data_types",
    srcs = glob(["*.py"]),
    deps = ["//third_party:pydantic"],
)
