load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "cost_functions",
    srcs = ["cost_functions.py"],
    deps = ["//third_party:numpy"],
)
